# tasks/main.yml

- name: Find disk with size 10GB
  set_fact:
    target_disk: "{{ item.key }}"
  loop: "{{ ansible_devices | dict2items }}"
  when: item.value.size == '10.00 GB'
  register: target_disks
  until: target_disks is success

- name: Display the disk name
  debug:
    msg: "The disk with size 10GB and not mounted is: /dev/{{ target_disk }}"
  when: target_disk is defined

- name: Create partition 1
  parted:
    device: "/dev/{{ target_disk }}"
    number: 1
    part_start: "{{ partition1_start }}"
    part_end: "{{ partition1_end }}"
    state: present

- name: Create partition 2
  parted:
    device: "/dev/{{ target_disk }}"
    number: 2
    part_start: "{{ partition2_start }}"
    part_end: "{{ partition2_end }}"
    state: present

- name: Make filesystem for partition 1
  filesystem:
    fstype: xfs
    dev: "/dev/{{ target_disk }}1"

- name: Make filesystem for partition 2
  filesystem:
    fstype: ext4
    dev: "/dev/{{ target_disk }}2"

- name: Create mount point for partition 1
  file:
    path: "{{ mount_point1 }}"
    state: directory

- name: Create mount point for partition 2
  file:
    path: "{{ mount_point2 }}"
    state: directory

- name: Mount partition 1
  mount:
    path: "{{ mount_point1 }}"
    src: "/dev/{{ target_disk }}1"
    fstype: xfs
    state: mounted

- name: Mount partition 2
  mount:
    path: "{{ mount_point2 }}"
    src: "/dev/{{ target_disk }}2"
    fstype: ext4
    state: mounted

- name: Persist partition 1 in fstab
  mount:
    path: "{{ mount_point1 }}"
    src: "/dev/{{ target_disk }}1"
    fstype: xfs
    opts: defaults
    state: present

- name: Persist partition 2 in fstab
  mount:
    path: "{{ mount_point2 }}"
    src: "/dev/{{ target_disk }}2"
    fstype: ext4
    opts: defaults
    state: present
